apiVersion: v1
kind: Template
metadata:
  name: elasticsearch

objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: elasticsearch

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: elasticsearch-build
  spec:
    triggers: 
      - type: ImageChange
      - type: ConfigChange
    source: 
      type: Git
      git:
        uri: https://github.com/docker-library/elasticsearch
      contextDir: "5/alpine"
    strategy: 
      type: Docker
      dockerStrategy:
    output: 
      to:
        kind: ImageStreamTag
        name: elasticsearch:latest
