apiVersion: v1
kind: Template
metadata:
  name: grafana

objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: grafana

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: grafana-build
  spec:
    triggers: 
      - type: ImageChange
      - type: ConfigChange
    source: 
      type: Git
      git:
        uri: https://github.com/OpenShiftDemos/grafana-openshift
    strategy: 
      type: Docker
      dockerStrategy:
    output: 
      to:
        kind: ImageStreamTag
        name: grafana:latest

