apiVersion: v1
items:
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: enmasse
    name: messaging
  spec:
    host: messaging.awesome.iot-playground.org
    port:
      targetPort: amqps
    tls:
      termination: passthrough
    to:
      kind: Service
      name: messaging
      weight: 100
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: enmasse
    name: mqtt
  spec:
    host: mqtt.awesome.iot-playground.org
    port:
      targetPort: secure-mqtt
    tls:
      termination: passthrough
    to:
      kind: Service
      name: mqtt
      weight: 100
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: enmasse
    name: restapi
  spec:
    host: api.awesome.iot-playground.org
    path: /v3/address
    port:
      targetPort: restapi
    to:
      kind: Service
      name: admin
      weight: 100
kind: List
metadata: {}
